import { Activity, BookOpen, Braces, Container, Database, EyeOff, Fingerprint, Globe2, Network, Radar, Route, Search, ShieldCheck } from "lucide-react";

export const tools = [
  { slug: "ping", name: "全球延迟", description: "从全球节点测量网络往返时延", names: { zh: "全球延迟", en: "Global latency", ja: "グローバル遅延", th: "เวลาแฝงทั่วโลก" }, descriptions: { zh: "从全球节点测量网络往返时延", en: "Measure round-trip latency from global probes", ja: "世界各地から往復遅延を測定", th: "วัดเวลาไปกลับจากจุดตรวจทั่วโลก" }, icon: Activity },
  { slug: "mtr", name: "MTR 路由", description: "定位跨境链路的丢包与绕行", names: { zh: "MTR 路由", en: "MTR routes", ja: "MTR ルート", th: "เส้นทาง MTR" }, descriptions: { zh: "定位跨境链路的丢包与绕行", en: "Locate packet loss and cross-border detours", ja: "国際回線の損失と迂回を特定", th: "ค้นหาการสูญเสียและเส้นทางอ้อม" }, icon: Route },
  { slug: "dns", name: "DNS 解析", description: "查询 A、AAAA、MX 与 TXT 记录", names: { zh: "DNS 解析", en: "DNS resolver", ja: "DNS 解析", th: "ตรวจสอบ DNS" }, descriptions: { zh: "查询 A、AAAA、MX 与 TXT 记录", en: "Query A, AAAA, MX, and TXT records", ja: "A、AAAA、MX、TXT レコードを照会", th: "ค้นหาระเบียน A, AAAA, MX และ TXT" }, icon: Network },
  { slug: "rdap", name: "RDAP 查询", description: "检索 IP 与域名注册信息", names: { zh: "RDAP 查询", en: "RDAP lookup", ja: "RDAP 照会", th: "ค้นหา RDAP" }, descriptions: { zh: "检索 IP 与域名注册信息", en: "Inspect IP and domain registration data", ja: "IP とドメインの登録情報を確認", th: "ตรวจสอบข้อมูลจดทะเบียน IP และโดเมน" }, icon: Database },
  { slug: "whois", name: "WHOIS", description: "查看网络资源注册资料", names: { zh: "WHOIS", en: "WHOIS", ja: "WHOIS", th: "WHOIS" }, descriptions: { zh: "查看网络资源注册资料", en: "View network resource registration data", ja: "ネットワーク資源の登録情報", th: "ดูข้อมูลจดทะเบียนทรัพยากรเครือข่าย" }, icon: Search },
  { slug: "censorship", name: "可达性检测", description: "对比多地区网站访问状态", names: { zh: "可达性检测", en: "Reachability", ja: "到達性診断", th: "การเข้าถึง" }, descriptions: { zh: "对比多地区网站访问状态", en: "Compare website reachability by region", ja: "地域別のサイト到達性を比較", th: "เปรียบเทียบการเข้าถึงเว็บไซต์ตามภูมิภาค" }, icon: Radar },
  { slug: "browser", name: "浏览器指纹", description: "检查浏览器暴露的环境信息", names: { zh: "浏览器指纹", en: "Browser fingerprint", ja: "ブラウザ指紋", th: "ลายนิ้วมือเบราว์เซอร์" }, descriptions: { zh: "检查浏览器暴露的环境信息", en: "Inspect exposed browser environment data", ja: "ブラウザが公開する環境情報", th: "ตรวจสอบข้อมูลสภาพแวดล้อมที่เปิดเผย" }, icon: Fingerprint },
  { slug: "rules", name: "代理规则", description: "验证代理分流规则是否生效", names: { zh: "代理规则", en: "Proxy rules", ja: "プロキシルール", th: "กฎพร็อกซี" }, descriptions: { zh: "验证代理分流规则是否生效", en: "Verify proxy routing policy", ja: "プロキシ分岐ルールを検証", th: "ตรวจสอบนโยบายการกำหนดเส้นทางพร็อกซี" }, icon: Braces },
  { slug: "security", name: "安全清单", description: "逐项完成网络安全检查", names: { zh: "安全清单", en: "Security checklist", ja: "安全チェック", th: "รายการความปลอดภัย" }, descriptions: { zh: "逐项完成网络安全检查", en: "Complete a practical network security review", ja: "実用的な安全確認を実施", th: "ตรวจสอบความปลอดภัยเครือข่าย" }, icon: ShieldCheck },
  { slug: "invisibility", name: "隐私暴露", description: "本地分析设备与浏览器隐私暴露", names: { zh: "隐私暴露", en: "Privacy exposure", ja: "プライバシー露出", th: "การเปิดเผยความเป็นส่วนตัว" }, descriptions: { zh: "本地分析设备与浏览器隐私暴露", en: "Audit device and browser exposure locally", ja: "端末とブラウザの露出をローカル分析", th: "วิเคราะห์การเปิดเผยอุปกรณ์ภายในเครื่อง" }, icon: EyeOff },
  { slug: "passport", name: "网络身份护照", description: "分析跨境网络身份信号一致性", names: { zh: "网络身份护照", en: "Network passport", ja: "ネットワークパスポート", th: "พาสปอร์ตเครือข่าย" }, descriptions: { zh: "分析跨境网络身份信号一致性", en: "Analyze cross-border identity signal consistency", ja: "国際ネットワークの ID 整合性を分析", th: "วิเคราะห์ความสอดคล้องของตัวตนเครือข่าย" }, icon: ShieldCheck },
  { slug: "cli", name: "CLI 文档", description: "在命令行调用 ElinksNet API", names: { zh: "CLI 文档", en: "CLI docs", ja: "CLI ドキュメント", th: "เอกสาร CLI" }, descriptions: { zh: "在命令行调用 ElinksNet API", en: "Call ElinksNet APIs from a terminal", ja: "ターミナルから API を利用", th: "เรียก ElinksNet API จากเทอร์มินัล" }, icon: BookOpen },
  { slug: "docker", name: "Docker 部署", description: "通过容器私有化部署服务", names: { zh: "Docker 部署", en: "Docker deploy", ja: "Docker 配備", th: "ติดตั้ง Docker" }, descriptions: { zh: "通过容器私有化部署服务", en: "Self-host the service with containers", ja: "コンテナでセルフホスト", th: "โฮสต์บริการด้วยคอนเทนเนอร์" }, icon: Container },
  { slug: "status", name: "服务状态", description: "查看数据源和平台可用性", names: { zh: "服务状态", en: "Service status", ja: "サービス状態", th: "สถานะบริการ" }, descriptions: { zh: "查看数据源和平台可用性", en: "View provider and platform availability", ja: "データ源と基盤の可用性", th: "ดูสถานะผู้ให้บริการและแพลตฟอร์ม" }, icon: Globe2 },
] as const;
