services:
  elinksnet:
    container_name: elinksnet
    image: elinksteam/elinksnet:latest
    restart: unless-stopped
    ports:
      - "18966:18966"
    environment:
      MAXMIND_ACCOUNT_ID: ""
      MAXMIND_LICENSE_KEY: ""
      MAXMIND_AUTO_UPDATE: "false"
      BACKEND_PORT: "11966"
      FRONTEND_PORT: "18966"
